## Construct sparse matrix A and save in a text file using ex9 of MFEM

Time dependent linear advection equation is:

\begin{equation}
\frac{\partial{u}}{\partial{t}} + v.{\nabla{u}} = 0
\end{equation}

Use discontinuous galerikin discretization to construct mass matrix M and advection matrix K in MFEM. Use the equation below to construct A so that A x = b.

\begin{equation}
A = M - (dt/2)*K
\end{equation}

In [1]:
import numpy as np
from scipy.sparse import coo_matrix

## Construct mass matrix M

In [2]:
# Load the data from the text file
M_ex9 = np.loadtxt('M_ex9.txt')

# Extract the row, column, and value arrays from the data
row_M = M_ex9[:, 0].astype(int)
col_M = M_ex9[:, 1].astype(int)
val_M = M_ex9[:, 2]

# Create the sparse matrix using COO format
M = coo_matrix((val_M, (row_M, col_M)))

print(M.shape)

(36865, 36865)


## Construct advection matrix K

In [3]:
# Load the data from the text file
K_ex9 = np.loadtxt('K_ex9.txt')

# Extract the row, column, and value arrays from the data
row_K = K_ex9[:, 0].astype(int)
col_K = K_ex9[:, 1].astype(int)
val_K = K_ex9[:, 2]

# Create the sparse matrix using COO format
K = coo_matrix((val_K, (row_K, col_K)))

print(K.shape)

(36865, 36865)


## Calculate sparse matrix A so that Ax=b

In [4]:
dt = 0.01
A = coo_matrix(M - (dt/2)*K)

print(A.shape)

(36865, 36865)


## Save matrix in a .txt file

In [5]:
# Save sparse matrix A to a text file
np.savetxt("A_ex9.txt", np.column_stack((A.row, A.col, A.data)))

# Print the saved matrix for verification
print(np.loadtxt("A_ex9.txt", dtype=float))

[[ 1.00000000e+00  1.00000000e+00  8.85771000e-06]
 [ 1.00000000e+00  2.00000000e+00  3.30107392e-06]
 [ 1.00000000e+00  3.00000000e+00 -3.30107304e-06]
 ...
 [ 3.68640000e+04  3.68620000e+04 -3.30054570e-06]
 [ 3.68640000e+04  3.68630000e+04  3.29985926e-06]
 [ 3.68640000e+04  3.68640000e+04  8.85827642e-06]]
